voucher_file: src/main/resources/csvFiles/voucherList.csv
blackList_file: src/main/resources/csvFiles/customer_blacklist.csv

spring:
  profiles:
    active: DB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # 데이터베이스 드라이버 클래스명
    url: jdbc:mysql://localhost:3306/kdt?serverTimezone=UTC&characterEncoding=UTF-8   # 데이터베이스 URL
    username: test                      # 데이터베이스 사용자 이름
    password: test1234!                       # 데이터베이스 비밀번호
