spring:
  config:
    activate:
      on-profile: local


---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:5431/devcourse
    username: root
    password: 303ehd
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver


jdbc:
  url: jdbc:mysql://localhost:5431/devcourse
  username: root
  password: 303ehd



---

spring:
  config:
    activate:
      on-profile: file

file:
  block-customer:
    path: store/
    stored-name: customer_blacklist
    stored-extension: .csv

  voucher:
    path: store/
    stored-name: voucher
    stored-extension: .csv