
file:
  customer:
    file-path: src/customer_blacklist.csv

spring:
  datasource:
    url: jdbc:mysql://localhost/voucher_app
    username: root
    password: root1234!

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: local
file:
  voucher:
    file-path: src/voucher_memory.csv

---


spring:
  config:
    activate:
      on-profile: jdbc
file:
  voucher:
    file-path: src/voucher_memory.csv
